### ISSUE TITLE
Email to Mozilla/Ford PIT group organizers 

### ISSUE THREAD

**Issue by dasaderi** [dasaderi/PIT_fellows_workgroup#1]
List of things to ask about in the email:

- [x] Special block rates for hotels
- Mozilla already said they don't have any
- Ford: TBA

- [x] London per diem

- [x] Are we offering per diem and accommodation for the whole MozFest week?

- [x] Info about who the survey was sent to – it seems Mozilla heavy so far

- [x] Send another reminder email

- [x] Access funding -- is it expensify/egencia, is it reimbursements, is through ford or someone else, is it split between orgs

**Comment by dariusk** [comment]
Email went out to Ford.

**Comment by dariusk** [comment]
Emailed Amy at Mozilla, too.

**Comment by dariusk** [comment]
Looks like Ford has 7 alumni but they have also just now pinged their current fellows. Michael says that since the fellowships last a lot longer than the other programs it could make sense to have current Ford program folks at the event.

Ford has no hotel block and no particular per diem guidance.

It looks like this is going to be reimbursement-based but they are looking into it and should get back to us by Wednesday.

**Comment by dariusk** [comment]
More info from Ford (which supercedes the above info):

> We can write up a guide that can be shared with recipients on how to request support once everything is confirmed if that is helpful; it is likely to include options for folks:
> - possible hotel block that people can sign up for (to be confirmed) - alumni is not responsible for hotel payment - there will be a deadline by which folks have to confirm to be in the block.
> - possible access to travel agent who will book and pay for flight (likely) - alumni is not responsible for flight payment - there will also be a deadline by which folks have to get flights booked
> - for folks who want to book their own travel and lodging and get reimbursed that is also an option. > You can request reimbursement after the flight is purchased, and then after the event so you don't have to be out of pocket for too long (it takes 6-8 weeks for payment after you submit your receipts, W-9 etc), or you can just submit all receipts at once after the conclusion of the event.
>- for folks who take advantage of the hotel block and travel agent they will have to keep receipts for ground transportation and per diem and get reimbursed after the event (after submitting receipts and W-9).

> Unfortunately we cannot do cash advances.

> We will confirm the process by September 3.

**Comment by dasaderi** [comment]
Survey was closed by @dariusk with 27 respondents.

**Comment by dasaderi** [comment]
Great! I'm going to close this issue.
