### ISSUE TITLE
Email Ford asknig about allocation of funding

### ISSUE THREAD

**Issue by dasaderi** [dasaderi/PIT_fellows_workgroup#6]
@dariusk, given that you have been in contact with Ford before, could you please email them to ask about how exactly we will be paying fellows? Ideally we can book flights and give stipend? Reimbursement is harder.

**Comment by dariusk** [comment]
We should hopefully hear back from them today!

**Comment by dariusk** [comment]
Got the response from MDF with details. Seems like it will be flights paid for up front, but reimbursement for hotel and incidentals. Closing this as the task is complete and I sent more info to the committee directly!
